version: '3.9'

services:
  postgres:
    image: postgres:12.9
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data:/var/lib/postgres/data

  adminer:
    image: adminer:4.8.1-standalone
    ports:
      - 8180:8080
    depends_on:
      - postgres
